name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  audioplayers: ^6.1.2
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  get: ^4.7.2
  google_fonts: ^6.2.1
  just_audio: ^0.9.46

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/home_page/
  - assets/start_page/
  - assets/home_page/carousel/
  - assets/home_page/discographyImages/
  - assets/home_page/popularSingles/
